import { IMeal, IMealComplete } from "../types";
import Ing from "./ingredients";

export interface MealsStringMap {
  [key: string]: IMeal;
}
export interface MealsStringMapComplete {
  [key: string]: IMealComplete;
}

/**
 * All meal keys and an enum
 */
export enum Meals {
  crispyChickenTenders = "crispyChickenTenders",
  chickenAsparagusRice = "chickenAsparagusRice",
  texMexMeatBallsRice = "texMexMeatBallsRice",
  creamyTuscanChicken = "creamyTuscanChicken",
  seseameStirFryBeef = "seseameStirFryBeef",
  chickenKievChipsSlaw = "chickenKievChipsSlaw",
  honeyMustardHamRoast = "honeyMustardHamRoast",
  curryChips = "curryChips",
  pizza = "pizza",
  sausagesPeasPotatosGravy = "sausagesPeasPotatosGravy",
  chickenBreadCrumbsCucumber = "chickenBreadCrumbsCucumber",
  curriedGoatRice = "curriedGoatRice",
  roastDinner = "roastDinner",
  garlicButterPrawnPasta = "garlicButterPrawnPasta",
  chickenPestoPasta = "chickenPestoPasta",
  burgerChips = "burgerChips",
  steakChips = "steakChips",
  salmonRice = "salmonRice",
  spagBol = "spagBol",
  hotdogs = "hotdogs",
  chickenKatsuCurry = "chickenKatsuCurry",
  paela = "paela",
  ramen = "ramen",
  pulledPorkTaco = "pulledPorkTaco",
  huntersChicken = "huntersChicken",
  beefStew = "beefStew",
  chilliConcarne = "chilliConcarne",
  lambStew = "lambStew",
  fajitas = "fajitas",
  soup = "soup",
  thai = "thai",
}

/**
 * All meals to be referenced
 */
export const allMeals: MealsStringMap = {
  [Meals.crispyChickenTenders]: {
    name: "Crispy Chicken Tenders",
    ingredients: [
      Ing.chicken,
      Ing.pankoBreadCrumbs,
      Ing.honey,
      Ing.chilli,
      Ing.eggs,
    ],
  },
  [Meals.chickenAsparagusRice]: {
    name: "Cheese & Garlic Chicken, Asparagus & Rice",
    ingredients: [Ing.chicken, Ing.asparagus, Ing.rice, Ing.cheese, Ing.garlic],
  },
  [Meals.texMexMeatBallsRice]: {
    name: "Tex Mex Meatballs & Rice",
    ingredients: [
      Ing.beefMince,
      Ing.cheese,
      Ing.pankoBreadCrumbs,
      Ing.parsley,
      Ing.garlic,
      Ing.eggs,
      Ing.cumin,
      Ing.onions,
      Ing.choppedTomatos,
    ],
  },
  [Meals.creamyTuscanChicken]: {
    name: "Creamy Tuscan Chicken",
    ingredients: [
      Ing.chicken,
      Ing.butter,
      Ing.parmesan,
      Ing.garlic,
      Ing.cherryTomato,
      Ing.spinach,
      Ing.doubleCream,
      Ing.parmesan,
    ],
  },
  [Meals.seseameStirFryBeef]: {
    name: "Seseame Beef Stir Fry",
    ingredients: [
      Ing.noodles,
      Ing.seseameSeeds,
      Ing.beef,
      Ing.beefStock,
      Ing.carrots,
      Ing.mangetout,
      Ing.garlic,
      Ing.soySauce,
      Ing.springOnions,
      Ing.ginger,
    ],
  },
  [Meals.chickenKievChipsSlaw]: {
    name: "Chicken Kiev, Chips & Coleslaw",
    ingredients: [Ing.chickenKiev, Ing.chips, Ing.coleslaw],
  },
  [Meals.honeyMustardHamRoast]: {
    name: "Honey Roast Gammon & Potatoes",
    ingredients: [Ing.gammonJoint, Ing.honey, Ing.potatos, Ing.brocolli],
  },
  [Meals.curryChips]: {
    name: "Curry & Chips",
    ingredients: [Ing.chips, Ing.chicken, Ing.tikkaMasala],
  },
  [Meals.pizza]: {
    name: "Pizza",
    ingredients: [Ing.pizza],
  },
  [Meals.sausagesPeasPotatosGravy]: {
    name: "Sausages, Peas & Potatoes",
    ingredients: [Ing.sausages, Ing.peas, Ing.potatos],
  },
  [Meals.chickenBreadCrumbsCucumber]: {
    name: "Chicken Breadcrumbs, Cucumber & Peppers",
    ingredients: [Ing.chicken, Ing.pankoBreadCrumbs, Ing.cucumber, Ing.peppers],
  },
  [Meals.curriedGoatRice]: {
    name: "Curried Goat & Rice",
    ingredients: [
      Ing.lamb,
      Ing.rice,
      Ing.curryPowder,
      Ing.celeary,
      Ing.coconutMilk,
      Ing.springOnions,
      Ing.garlic,
      Ing.ginger,
      Ing.onions,
      Ing.tomatoPaste,
      Ing.scotchBonnet,
    ],
  },
  [Meals.roastDinner]: {
    name: "Roast Dinner",
    ingredients: [
      Ing.potatos,
      Ing.yorkshirePuddings,
      Ing.carrots,
      Ing.swede,
      Ing.meat,
      Ing.brocolli,
      Ing.cabbage,
      Ing.cauliflowerCheese,
      Ing.gravyGranules,
    ],
  },
  [Meals.garlicButterPrawnPasta]: {
    name: "Garlic Butter Prawn Pasta",
    ingredients: [
      Ing.garlic,
      Ing.prawns,
      Ing.thyme,
      Ing.rosemary,
      Ing.butter,
      Ing.tagliatelle,
    ],
  },
  [Meals.chickenPestoPasta]: {
    name: "Chicken Pesto Pasta",
    ingredients: [
      Ing.chicken,
      Ing.pesto,
      Ing.mayo,
      Ing.cherryTomato,
      Ing.fusilli,
    ],
  },
  [Meals.burgerChips]: {
    name: "Burger & Chips",
    ingredients: [
      Ing.burgers,
      Ing.burgerBuns,
      Ing.onions,
      Ing.lettuce,
      Ing.bacon,
      Ing.cheese,
      Ing.chips,
      Ing.mayo,
    ],
  },
  [Meals.steakChips]: {
    name: "Steak & Chips",
    ingredients: [Ing.steak, Ing.chips, Ing.tenderstemBroccoli],
  },
  [Meals.salmonRice]: {
    name: "Salmon & Rice",
    ingredients: [
      Ing.salmon,
      Ing.rice,
      Ing.asparagus,
      Ing.pesto,
      Ing.doubleCream,
    ],
  },
  [Meals.spagBol]: {
    name: "Spaghetti Bolognese",
    ingredients: [
      Ing.spaghetti,
      Ing.garlic,
      Ing.beefMince,
      Ing.choppedTomatos,
      Ing.beefStock,
      Ing.cheese,
      Ing.onions,
      Ing.peppers,
    ],
  },
  [Meals.hotdogs]: {
    name: "Hotdogs",
    ingredients: [Ing.hotdogBuns, Ing.hotdogs, Ing.onions],
  },
  [Meals.chickenKatsuCurry]: {
    name: "Chicken Katsu Curry",
    ingredients: [Ing.chicken, Ing.katsuCurrySauce, Ing.rice, Ing.springOnions],
  },
  [Meals.paela]: {
    name: "Paela",
    ingredients: [
      Ing.rice,
      Ing.peppers,
      Ing.chorizo,
      Ing.garlic,
      Ing.whiteWine,
      Ing.choppedTomatos,
      Ing.tomatoPaste,
      Ing.thyme,
    ],
  },
  [Meals.ramen]: {
    name: "Ramen",
    ingredients: [
      Ing.carrots,
      Ing.onions,
      Ing.chickenStock,
      Ing.noddles,
      Ing.beanSprouts,
      Ing.sweetCorn,
      Ing.bambooShoots,
      Ing.springOnions,
      Ing.leeks,
    ],
  },
  [Meals.pulledPorkTaco]: {
    name: "Pulled Pork Tacos",
    ingredients: [
      Ing.porkFillet,
      Ing.onions,
      Ing.garlic,
      Ing.paprika,
      Ing.oregano,
      Ing.garlicPowder,
      Ing.cumin,
      Ing.oliveOil,
      Ing.oranges,
      Ing.pinappleJuice,
      Ing.orangeJuice,
      Ing.tacos,
      Ing.redOnions,
      Ing.lime,
      Ing.cheese,
      Ing.lettuce,
      Ing.cucumber,
      Ing.peppers,
      Ing.salsa,
      Ing.guacamole,
      Ing.sourCream,
    ],
  },
  [Meals.huntersChicken]: {
    name: "Hunters Chicken & Rice",
    ingredients: [
      Ing.chicken,
      Ing.bacon,
      Ing.cheese,
      Ing.rice,
      Ing.bbqSauce,
      Ing.brocolli,
      Ing.asparagus,
    ],
  },
  [Meals.beefStew]: {
    name: "Beef Stew",
    ingredients: [
      Ing.beef,
      Ing.baconLardons,
      Ing.beefStock,
      Ing.redWine,
      Ing.carrots,
      Ing.potatos,
      Ing.parsnips,
      Ing.tomatoPaste,
      Ing.onions,
      Ing.garlic,
      Ing.thyme,
    ],
  },
  [Meals.lambStew]: {
    name: "Lamb Stew",
    ingredients: [
      Ing.lamb,
      Ing.baconLardons,
      Ing.lambStock,
      Ing.redWine,
      Ing.carrots,
      Ing.potatos,
      Ing.parsnips,
      Ing.tomatoPaste,
      Ing.onions,
      Ing.garlic,
      Ing.thyme,
    ],
  },
  [Meals.chilliConcarne]: {
    name: "Chilli Con Carne & Rice",
    ingredients: [
      Ing.beefMince,
      Ing.beefStock,
      Ing.cumin,
      Ing.sourCream,
      Ing.paprika,
      Ing.choppedTomatos,
      Ing.rice,
      Ing.onions,
      Ing.chilli,
      Ing.garlic,
      Ing.peppers,
      Ing.kidneyBeans,
    ],
  },
  [Meals.fajitas]: {
    name: "Fajitas",
    ingredients: [
      Ing.chicken,
      Ing.peppers,
      Ing.onions,
      Ing.lettuce,
      Ing.cucumber,
      Ing.cheese,
      Ing.cumin,
      Ing.paprika,
      Ing.oregano,
    ],
  },
  [Meals.soup]: {
    name: "Soup",
    ingredients: [Ing.soup, Ing.bread],
  },
  [Meals.thai]: {
    name: "Thai & Rice",
    ingredients: [
      Ing.rice,
      Ing.meat,
      Ing.ginger,
      Ing.garlic,
      Ing.coconutMilk,
      Ing.lemonGrass,
      Ing.miniSweatCorn,
      Ing.mangetout,
      Ing.thaiPaste,
    ],
  },
};
